create table author(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(60) NOT NULL
);

insert into author(id, name) values 
    (1, 'L. Tolstoy' ),
    (2, 'V. Kaverin'),
    (3, 'D. London');

create table book(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(60) NOT NULL,
    authorId integer references author(id)
);

insert into book(title, authorId ) values 
    ('Vojna i Mir', 1 ),
    ('Dwa Kapitana', 2),
    ('Marcin Iden', 3),
    ('Anna Karenina', 1);


create table users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(60) NOT NULL,
    password varchar(200) NOT NULL,
    role varchar(10) NOT NULL
);

insert into users(username, password, role ) values 
    ('alex', '$2b$10$fHaatSR92BVf4WMZpiCbUOSqoyXJUPTgNcDXzjSsB74B9FaTDM6Hi', 'admin' ),
    ('alex2', '$2b$10$dFodc/2AOV7Hyo4YHzTDCelp6JjQ3BSxl.dO7Dqeyilm.MbOk/TF2', 'user');
