version: "3.9"
name: "book-app"
services:
  postgresdb:
    image: postgres:17.4
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_DATABASE
    ports:
      - ${POSTGRES_DB_LOCAL_PORT}:${POSTGRES_DB_DOCKER_PORT}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", $POSTGRES_DB_DATABASE, "-U", $POSTGRES_DB_USER]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - POSTGRES_DB_HOST=$POSTGRES_DB_HOST
      - POSTGRES_DB_USER=$POSTGRES_DB_USER
      - POSTGRES_DB_ROOT_PASSWORD=$POSTGRES_DB_ROOT_PASSWORD
      - POSTGRES_DB_DATABASE=$POSTGRES_DB_DATABASE
      - POSTGRES_DB_DOCKER_PORT=$POSTGRES_DB_DOCKER_PORT
    depends_on:
      postgresdb:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - ${PGADMIN_LOCAL_PORT}:${PGADMIN_DOCKER_PORT}
    environment:
      PGADMIN_DEFAULT_EMAIL: user@g.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes: 
  pgadmin-data: