openapi: 3.0.0
info:
  title: Book API
  description: API for managing books
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /books:
    get:
      summary: Retrieve a list of books
      responses:
        200:
          description: A list of books.
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The created book.
        400:
          description: Validation error.
        500:
          description: Server error.
    put:
      summary: Update a book
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        200:
          description: Book is updated.
        400:
          description: Validation error.
        500:
          description: Server error.
  /books/{authorName}:
    get:
      summary: Get book by authorName
      parameters:
        - in: path
          name: authorName
          required: true
          schema:
            type: string
      responses:
        200:
          description: A list of book objects.
        400:
          description: Validation error.
        500:
          description: Server error.
  /books/{id}:
    get:
      summary: Get book by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: A single book object.
        400:
          description: Validation error.
        500:
          description: Server error.
    delete:
      summary: Delete a book
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Book deleted.
        400:
          description: Validation error.
        500:
          description: Server error.
components:
  schemas:
    Book:
      type: object
      properties:
        title:
          type: string
          example: Vojna i Mir
        authorId:
          type: string
          example: 1
        id:
          type: string
          example: 1
